name: app_avaliability
description: Fix of Flutter plugin that allows you to check if an app is installed/enabled, launch an app and get the list of installed apps.
version: 0.0.1
homepage: https://github.com/nestorsgarzonc/flutter_appavailability

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.app_avaliability
        pluginClass: AppAvaliabilityPlugin
      ios:
        pluginClass: AppAvaliabilityPlugin
